import React, { useMemo, useState } from 'react';
import { ClipboardList, Plus, Search, Filter, Pencil, Trash2, CheckCircle2, XCircle, LogOut, RotateCcw, X } from 'lucide-react';
import { Student, Tablet, TabletAssignment, UserRole, TabletMovement } from '../../types';
import { logAuditAction } from '../../utils/storage';

interface Props {
  movements: TabletMovement[];
  students: Student[];
  tablets: Tablet[];
  assignments: TabletAssignment[];
  activeRole: UserRole;
  onSave: (items: TabletMovement[]) => Promise<void> | void;
}

const statusClass: Record<TabletMovement['status'], string> = {
  PENDING:'bg-amber-50 text-amber-700 border-amber-200', APPROVED:'bg-blue-50 text-blue-700 border-blue-200',
  REJECTED:'bg-rose-50 text-rose-700 border-rose-200', OUTSIDE:'bg-violet-50 text-violet-700 border-violet-200',
  RETURNED:'bg-emerald-50 text-emerald-700 border-emerald-200', OVERDUE:'bg-red-50 text-red-700 border-red-200'
};
const today=()=>new Date().toISOString().slice(0,10);
const effectiveStatus=(m:TabletMovement):TabletMovement['status']=>m.status==='OUTSIDE'&&m.expectedReturnDate<today()?'OVERDUE':m.status;

export const TabletMovementManagement:React.FC<Props>=({movements,students,tablets,assignments,activeRole,onSave})=>{
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('ALL');
  const [editing,setEditing]=useState<TabletMovement|null>(null); const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false);

  const activeAssignments=useMemo(()=>assignments.filter(a=>a.status==='Active'),[assignments]);
  const list=useMemo(()=>movements.filter(m=>{const q=search.toLowerCase();const s=effectiveStatus(m);return (status==='ALL'||s===status)&&[m.studentName,m.tabletName,m.tabletNumber,m.movementType].join(' ').toLowerCase().includes(q)}),[movements,search,status]);
  const save=async(next:TabletMovement[])=>{setSaving(true);try{await onSave(next);}finally{setSaving(false)}};
  const changeStatus=async(id:string,next:TabletMovement['status'])=>{const item=movements.find(x=>x.id===id);if(!item)return;await save(movements.map(x=>x.id===id?{...x,status:next,updatedAt:new Date().toISOString()}:x));await logAuditAction('System User',activeRole,'TABLET_MOVEMENT_STATUS','Tablet Movement',`${item.tabletNumber}: ${item.status} → ${next}`);};
  const remove=async(item:TabletMovement)=>{if(!confirm(`Delete movement record for ${item.studentName}?`))return;await save(movements.filter(x=>x.id!==item.id));await logAuditAction('System User',activeRole,'TABLET_MOVEMENT_DELETED','Tablet Movement',`Deleted movement ${item.id}`);};
  const openAdd=()=>{setEditing(null);setShowForm(true)}; const openEdit=(m:TabletMovement)=>{setEditing(m);setShowForm(true)};

  return <div className="max-w-[1600px] mx-auto space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-black text-slate-900"><ClipboardList className="w-6 h-6 text-blue-600"/>Tablet Movement</h1><p className="mt-1 text-sm text-slate-500">Connected with active student tablet assignments.</p></div><button onClick={openAdd} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700"><Plus className="w-4 h-4"/>Add Movement</button></div>

    {showForm&&<MovementForm students={students} tablets={tablets} assignments={activeAssignments} initial={editing} onCancel={()=>{setShowForm(false);setEditing(null)}} onSave={async(data)=>{const now=new Date().toISOString();const next=editing?movements.map(x=>x.id===editing.id?{...editing,...data,updatedAt:now}:x):[{...data,id:`movement-${Date.now()}`,status:'PENDING' as const,requestDate:today(),createdAt:now,updatedAt:now},...movements];await save(next);await logAuditAction('System User',activeRole,editing?'TABLET_MOVEMENT_UPDATED':'TABLET_MOVEMENT_CREATED','Tablet Movement',`${data.studentName} - ${data.tabletNumber}`);setShowForm(false);setEditing(null)}}/>}

    <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
      <div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search student, tablet or movement type..." className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-blue-500"/></div><div className="relative"><Filter className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 py-2.5 pl-9 pr-8 text-sm"><option value="ALL">All Status</option>{['PENDING','APPROVED','REJECTED','OUTSIDE','RETURNED','OVERDUE'].map(x=><option key={x}>{x}</option>)}</select></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="p-4">Student</th><th className="p-4">Tablet</th><th className="p-4">Type</th><th className="p-4">Start</th><th className="p-4">Return</th><th className="p-4">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{list.length===0?<tr><td colSpan={7} className="p-12 text-center text-sm text-slate-500">No movement records found.</td></tr>:list.map(m=>{const s=effectiveStatus(m);return <tr key={m.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="p-4"><div className="font-bold text-slate-800">{m.studentName}</div><div className="text-xs text-slate-500">{m.pinNumber}</div></td><td className="p-4"><div className="font-semibold">{m.tabletName}</div><div className="text-xs text-slate-500">{m.tabletNumber}</div></td><td className="p-4 text-sm">{m.movementType}</td><td className="p-4 text-sm">{m.startDate}</td><td className="p-4 text-sm">{m.expectedReturnDate}</td><td className="p-4"><span className={`rounded-full border px-2.5 py-1 text-[11px] font-black ${statusClass[s]}`}>{s}</span></td><td className="p-4"><div className="flex justify-end gap-1"><button onClick={()=>openEdit(m)} title="Edit" className="rounded-lg p-2 text-blue-600 hover:bg-blue-50"><Pencil className="w-4 h-4"/></button><button onClick={()=>remove(m)} title="Delete" className="rounded-lg p-2 text-rose-600 hover:bg-rose-50"><Trash2 className="w-4 h-4"/></button>{s==='PENDING'&&<><button onClick={()=>changeStatus(m.id,'APPROVED')} title="Approve" className="rounded-lg p-2 text-emerald-600 hover:bg-emerald-50"><CheckCircle2 className="w-4 h-4"/></button><button onClick={()=>changeStatus(m.id,'REJECTED')} title="Reject" className="rounded-lg p-2 text-rose-600 hover:bg-rose-50"><XCircle className="w-4 h-4"/></button></>}{s==='APPROVED'&&<button onClick={()=>changeStatus(m.id,'OUTSIDE')} title="Check Out" className="rounded-lg p-2 text-violet-600 hover:bg-violet-50"><LogOut className="w-4 h-4"/></button>}{(s==='OUTSIDE'||s==='OVERDUE')&&<button onClick={()=>changeStatus(m.id,'RETURNED')} title="Check In" className="rounded-lg p-2 text-emerald-600 hover:bg-emerald-50"><RotateCcw className="w-4 h-4"/></button>}</div></td></tr>})}</tbody></table></div>
    </div>{saving&&<div className="fixed bottom-5 right-5 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white shadow-xl">Saving...</div>}
  </div>
}

const MovementForm:React.FC<{students:Student[];tablets:Tablet[];assignments:TabletAssignment[];initial:TabletMovement|null;onCancel:()=>void;onSave:(data:any)=>Promise<void>}> = ({assignments,initial,onCancel,onSave})=>{
  const [assignmentId,setAssignmentId]=useState(initial?.assignmentId||''); const [type,setType]=useState(initial?.movementType||'Vacation'); const [startDate,setStartDate]=useState(initial?.startDate||today()); const [expectedReturnDate,setExpectedReturnDate]=useState(initial?.expectedReturnDate||''); const [destination,setDestination]=useState(initial?.destination||''); const [reason,setReason]=useState(initial?.reason||''); const [notes,setNotes]=useState(initial?.notes||''); const [error,setError]=useState('');
  const assignment=assignments.find(a=>a.id===assignmentId)||assignments.find(a=>a.studentId===initial?.studentId&&a.tabletId===initial?.tabletId);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!assignment){setError('Please select an active student tablet assignment.');return}if(expectedReturnDate<=startDate){setError('Expected return date must be after start date.');return}setError('');await onSave({assignmentId:assignment.id,studentId:assignment.studentId,studentName:assignment.studentName,pinNumber:assignment.pinNumber,tabletId:assignment.tabletId,tabletName:assignment.tabletName,tabletNumber:assignment.tabletNumber,movementType:type,startDate,expectedReturnDate,destination,reason,notes});};
  return <form onSubmit={submit} className="rounded-2xl border border-blue-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black text-slate-900">{initial?'Edit':'Add'} Tablet Movement</h2><p className="text-xs text-slate-500">Select the assigned student; tablet details are connected automatically.</p></div><button type="button" onClick={onCancel} className="rounded-lg p-2 hover:bg-slate-100"><X className="w-4 h-4"/></button></div>
    <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-xs font-bold text-slate-600">Student & Assigned Tablet<select required value={assignmentId} onChange={e=>setAssignmentId(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Select active assignment</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.studentName} — {a.tabletNumber}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Movement Type<select value={type} onChange={e=>setType(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{['Vacation','Take Home','Holiday','Educational Purpose','Other'].map(x=><option key={x}>{x}</option>)}</select></label>
    {assignment&&<><div className="rounded-xl bg-slate-50 p-3 text-sm"><span className="text-xs text-slate-500">Student PIN</span><div className="font-bold">{assignment.pinNumber}</div></div><div className="rounded-xl bg-slate-50 p-3 text-sm"><span className="text-xs text-slate-500">Tablet</span><div className="font-bold">{assignment.tabletName} ({assignment.tabletNumber})</div></div></>}
    <label className="text-xs font-bold text-slate-600">Start Date<input required type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="text-xs font-bold text-slate-600">Expected Return Date<input required type="date" value={expectedReturnDate} onChange={e=>setExpectedReturnDate(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label>
    <label className="text-xs font-bold text-slate-600">Destination<input required value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Where will the tablet go?" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="text-xs font-bold text-slate-600">Reason<input required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for movement" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="text-xs font-bold text-slate-600 md:col-span-2">Notes (Optional)<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={2} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label></div>
    {error&&<div className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-medium text-red-700">{error}</div>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold">Cancel</button><button className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-blue-700">{initial?'Update Movement':'Save Movement'}</button></div>
  </form>
}