import React, { useMemo, useState } from 'react';
import { ClipboardList, Plus, Search, Pencil, Trash2, CheckCircle2, XCircle, LogOut, RotateCcw, X, UserRound, Tablet as TabletIcon } from 'lucide-react';
import { Student, Tablet, TabletAssignment, UserRole, TabletMovement } from '../../types';
import { logAuditAction } from '../../utils/storage';
import { deleteCollectionRecord } from '../../lib/db';

interface Props { movements: TabletMovement[]; students: Student[]; tablets: Tablet[]; assignments: TabletAssignment[]; activeRole: UserRole; onSave: (items: TabletMovement[]) => Promise<void> | void; }
type Candidate = { id:string; assignmentId:string; studentId:string; studentName:string; studentPin:string; email:string; standard:string; pinNumber:string; tabletId:string; tabletName:string; tabletNumber:string };
const today=()=>new Date().toISOString().slice(0,10);
const currentStatus=(m:TabletMovement):TabletMovement['status']=>m.status==='OUTSIDE'&&m.expectedReturnDate<today()?'OVERDUE':m.status;
const badge:Record<TabletMovement['status'],string>={PENDING:'bg-amber-50 text-amber-700 border-amber-200',APPROVED:'bg-blue-50 text-blue-700 border-blue-200',REJECTED:'bg-rose-50 text-rose-700 border-rose-200',OUTSIDE:'bg-violet-50 text-violet-700 border-violet-200',RETURNED:'bg-emerald-50 text-emerald-700 border-emerald-200',OVERDUE:'bg-red-50 text-red-700 border-red-200'};

function buildCandidates(students:Student[],tablets:Tablet[],assignments:TabletAssignment[]):Candidate[]{
 const result:Candidate[]=[]; const used=new Set<string>();
 const findStudent=(id:string,name?:string)=>students.find(s=>String(s.id)===String(id))||students.find(s=>String(s.name??'').trim().toLowerCase()===String(name??'').trim().toLowerCase());
 const add=(c:Candidate)=>{const key=c.studentId+'|'+c.tabletId;if(!c.studentId||!c.tabletId||used.has(key))return;used.add(key);result.push(c);};
 assignments.filter(a=>String(a.status??'').toLowerCase()!=='returned').forEach(a=>{const s=findStudent(String(a.studentId??''),a.studentName);add({id:'assignment-'+a.id,assignmentId:a.id,studentId:String(a.studentId??''),studentName:String(a.studentName??s?.name??'Student'),studentPin:String(s?.studentPin??(a as any).studentPin??''),email:String(s?.email??''),standard:String(s?.standard??a.standard??''),pinNumber:String(a.pinNumber??s?.pinNumber??''),tabletId:String(a.tabletId??a.tabletNumber??''),tabletName:String(a.tabletName??a.tabletNumber??'Tablet'),tabletNumber:String(a.tabletNumber??a.tabletName??'')});});
 students.forEach(s=>{const id=String(s.assignedTabletId??'').trim(),num=String(s.assignedTabletNumber??'').trim();const t=tablets.find(x=>String(x.id)===id)||tablets.find(x=>String(x.tabletNumber).trim().toLowerCase()===num.toLowerCase())||tablets.find(x=>String(x.assignedToStudentId??'')===String(s.id))||tablets.find(x=>String(x.assignedToStudentName??'').trim().toLowerCase()===String(s.name??'').trim().toLowerCase());if(t)add({id:'linked-'+s.id+'-'+t.id,assignmentId:'linked-'+s.id+'-'+t.id,studentId:s.id,studentName:s.name,studentPin:String(s.studentPin??''),email:String(s.email??''),standard:String(s.standard??''),pinNumber:s.pinNumber,tabletId:t.id,tabletName:t.tabletName||t.tabletNumber,tabletNumber:t.tabletNumber});});
 tablets.filter(t=>Boolean(t.assignedToStudentId||t.assignedToStudentName)||String(t.status).toLowerCase()==='assigned').forEach(t=>{const id=String(t.assignedToStudentId??'').trim(),s=findStudent(id,t.assignedToStudentName),sid=id||s?.id||'',name=String(t.assignedToStudentName??s?.name??'').trim();if(!sid||!name)return;add({id:'tablet-link-'+t.id,assignmentId:'tablet-link-'+t.id,studentId:sid,studentName:name,studentPin:String(s?.studentPin??''),email:String(s?.email??''),standard:String(s?.standard??''),pinNumber:String(s?.pinNumber??''),tabletId:t.id,tabletName:t.tabletName||t.tabletNumber,tabletNumber:t.tabletNumber});});
 return result.sort((a,b)=>a.studentName.localeCompare(b.studentName));
}

export const TabletMovementManagement:React.FC<Props>=({movements,students,tablets,assignments,activeRole,onSave})=>{
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<TabletMovement|null>(null),[search,setSearch]=useState(''),[saving,setSaving]=useState(false),[deleteTarget,setDeleteTarget]=useState<TabletMovement|null>(null);
 const candidates=useMemo(()=>buildCandidates(students,tablets,assignments),[students,tablets,assignments]);
 const list=useMemo(()=>movements.filter(m=>[m.studentName,m.tabletName,m.tabletNumber,m.movementType,m.status].join(' ').toLowerCase().includes(search.toLowerCase())),[movements,search]);
 const persist=async(next:TabletMovement[])=>{setSaving(true);try{await onSave(next);}finally{setSaving(false);}};
 const updateStatus=async(m:TabletMovement,status:TabletMovement['status'])=>{await persist(movements.map(x=>x.id===m.id?{...x,status,updatedAt:new Date().toISOString()}:x));await logAuditAction('System User',activeRole,'TABLET_MOVEMENT_STATUS','Tablet Movement',m.tabletNumber+' → '+status);};
 const remove=async()=>{if(!deleteTarget)return;const m=deleteTarget;setSaving(true);try{await deleteCollectionRecord('movements',m.id);await onSave(movements.filter(x=>x.id!==m.id));await logAuditAction('System User',activeRole,'TABLET_MOVEMENT_DELETED','Tablet Movement',m.tabletNumber);setDeleteTarget(null);}finally{setSaving(false);}};
 return <div className="max-w-[1500px] mx-auto space-y-5">
  <div className="flex items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-black text-slate-900"><ClipboardList className="w-6 h-6 text-blue-600"/>Tablet Movement</h1><p className="text-sm text-slate-500 mt-1">Simple tablet outside movement tracking.</p></div><button onClick={()=>{setEditing(null);setOpen(true)}} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700"><Plus className="w-4 h-4"/>Add Movement</button></div>
  {open&&<MovementForm candidates={candidates} movements={movements} initial={editing} onCancel={()=>{setOpen(false);setEditing(null)}} onSave={async data=>{const now=new Date().toISOString();const next=editing?movements.map(x=>x.id===editing.id?{...editing,...data,updatedAt:now}:x):[{...data,id:'movement-'+Date.now(),requestDate:today(),status:'PENDING' as const,createdAt:now,updatedAt:now},...movements];await persist(next);await logAuditAction('System User',activeRole,editing?'TABLET_MOVEMENT_UPDATED':'TABLET_MOVEMENT_CREATED','Tablet Movement',data.studentName+' - '+data.tabletNumber);setOpen(false);setEditing(null)}}/>}
  <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden"><div className="p-4 border-b border-slate-100"><div className="relative max-w-xl"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search student or tablet..." className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-blue-500"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="p-4">Student</th><th className="p-4">Tablet</th><th className="p-4">Type</th><th className="p-4">Dates</th><th className="p-4">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{list.length===0?<tr><td colSpan={6} className="p-12 text-center text-sm text-slate-500">No movement records found.</td></tr>:list.map(m=>{const s=currentStatus(m);return <tr key={m.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="p-4 font-semibold">{m.studentName}</td><td className="p-4"><div className="font-semibold">{m.tabletName}</div><div className="text-xs text-slate-500">{m.tabletNumber}</div></td><td className="p-4 text-sm">{m.movementType}</td><td className="p-4 text-sm"><div>{m.startDate}</div><div className="text-xs text-slate-500">Return: {m.expectedReturnDate}</div></td><td className="p-4"><span className={'rounded-full border px-2.5 py-1 text-[11px] font-bold '+badge[s]}>{s}</span></td><td className="p-4"><div className="flex justify-end gap-1"><button onClick={()=>{setEditing(m);setOpen(true)}} title="Edit" className="p-2 rounded-lg text-blue-600 hover:bg-blue-50"><Pencil className="w-4 h-4"/></button><button onClick={()=>setDeleteTarget(m)} title="Delete" className="p-2 rounded-lg text-rose-600 hover:bg-rose-50"><Trash2 className="w-4 h-4"/></button>{s==='PENDING'&&<><button onClick={()=>updateStatus(m,'APPROVED')} title="Approve" className="p-2 rounded-lg text-emerald-600 hover:bg-emerald-50"><CheckCircle2 className="w-4 h-4"/></button><button onClick={()=>updateStatus(m,'REJECTED')} title="Reject" className="p-2 rounded-lg text-rose-600 hover:bg-rose-50"><XCircle className="w-4 h-4"/></button></>}{s==='APPROVED'&&<button onClick={()=>updateStatus(m,'OUTSIDE')} title="Check Out" className="p-2 rounded-lg text-violet-600 hover:bg-violet-50"><LogOut className="w-4 h-4"/></button>}{(s==='OUTSIDE'||s==='OVERDUE')&&<button onClick={()=>updateStatus(m,'RETURNED')} title="Return" className="p-2 rounded-lg text-emerald-600 hover:bg-emerald-50"><RotateCcw className="w-4 h-4"/></button>}</div></td></tr>})}</tbody></table></div></div>
  {saving&&<div className="fixed bottom-5 right-5 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Saving...</div>}
  {deleteTarget&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-rose-100 text-rose-600"><Trash2 className="h-6 w-6"/></div><div className="flex-1"><h3 className="text-lg font-black text-slate-900">Delete Tablet Movement?</h3><p className="mt-2 text-sm leading-6 text-slate-600">Are you sure you want to delete this tablet movement record? This action cannot be undone.</p><div className="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-700"><b>{deleteTarget.tabletName}</b> ({deleteTarget.tabletNumber})</div></div></div><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={saving} onClick={()=>setDeleteTarget(null)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Cancel</button><button type="button" disabled={saving} onClick={remove} className="rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-rose-700">{saving?'Deleting...':'Yes, Delete'}</button></div></div></div>}
 </div>;
};

const MovementForm:React.FC<{candidates:Candidate[];movements:TabletMovement[];initial:TabletMovement|null;onCancel:()=>void;onSave:(data:any)=>Promise<void>}> = ({candidates,movements,initial,onCancel,onSave})=>{
 const initialCandidate=initial?candidates.find(c=>c.studentId===initial.studentId&&c.tabletId===initial.tabletId):undefined;
 const [pinSearch,setPinSearch]=useState(initialCandidate?.studentPin||'');
 const [candidateId,setCandidateId]=useState(initialCandidate?.id||'');
 const [movementType,setMovementType]=useState(initial?.movementType||'Vacation');
 const [startDate,setStartDate]=useState(initial?.startDate||today());
 const [returnDate,setReturnDate]=useState(initial?.expectedReturnDate||'');
 const [note,setNote]=useState(initial?.notes||'');
 const [error,setError]=useState('');
 const selected=candidates.find(c=>c.id===candidateId);
 const matches=useMemo(()=>{const q=pinSearch.trim().toLowerCase();return q?candidates.filter(c=>c.studentPin.trim().toLowerCase().includes(q)).slice(0,6):[]},[candidates,pinSearch]);
 const handlePin=(value:string)=>{setPinSearch(value);const exact=candidates.filter(c=>c.studentPin.trim().toLowerCase()===value.trim().toLowerCase());if(exact.length===1)setCandidateId(exact[0].id);else if(!value.trim()||!selected||selected.studentPin.trim().toLowerCase()!==value.trim().toLowerCase())setCandidateId('');};
 const selectCandidate=(c:Candidate)=>{setCandidateId(c.id);setPinSearch(c.studentPin);setError('');};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!selected){setError('Please search and select a valid Student PIN.');return;}if(!returnDate||returnDate<=startDate){setError('Expected return date must be after the start date.');return;}const active=movements.some(m=>m.id!==initial?.id&&m.tabletId===selected.tabletId&&['PENDING','APPROVED','OUTSIDE','OVERDUE'].includes(currentStatus(m)));if(active){setError('This tablet already has an active movement record.');return;}await onSave({assignmentId:selected.assignmentId,studentId:selected.studentId,studentName:selected.studentName,pinNumber:selected.pinNumber,tabletId:selected.tabletId,tabletName:selected.tabletName,tabletNumber:selected.tabletNumber,movementType,startDate,expectedReturnDate:returnDate,destination:initial?.destination||'',reason:initial?.reason||'',notes:note});};
 return <form onSubmit={submit} className="rounded-2xl border border-blue-200 bg-white shadow-sm overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-lg font-black text-slate-900">{initial?'Edit':'Add'} Tablet Movement</h2><p className="mt-0.5 text-xs text-slate-500">Search by Student PIN and enter only the essential movement details.</p></div><button type="button" onClick={onCancel} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X className="h-4 w-4"/></button></div><div className="space-y-5 p-5">
  <div><label className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-600">Student PIN</label><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input autoFocus value={pinSearch} onChange={e=>handlePin(e.target.value)} placeholder="Enter Student PIN..." inputMode="numeric" className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-4 text-sm font-semibold text-slate-900 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></div>{pinSearch.trim()&&!selected&&matches.length>0&&<div className="mt-2 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-lg">{matches.map(c=><button key={c.id} type="button" onClick={()=>selectCandidate(c)} className="flex w-full items-center gap-3 border-b border-slate-100 px-4 py-3 text-left last:border-b-0 hover:bg-blue-50"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-blue-100 text-blue-700"><UserRound className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold text-slate-900">{c.studentName}</span><span className="block text-xs text-slate-500">PIN: {c.studentPin} • {c.tabletNumber}</span></span></button>)}</div>}{pinSearch.trim()&&!selected&&matches.length===0&&<div className="mt-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-700">No student found with this PIN.</div>}</div>
  {selected&&<div className="rounded-2xl border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-4"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-600 text-white"><UserRound className="h-4 w-4"/></span><div><p className="text-xs font-bold uppercase tracking-wide text-blue-600">Student Details</p><p className="text-sm font-black text-slate-900">Student found</p></div></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-700">Ready</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-[11px] font-semibold uppercase text-slate-400">Student Name</p><p className="mt-1 text-sm font-bold text-slate-900">{selected.studentName}</p></div><div><p className="text-[11px] font-semibold uppercase text-slate-400">Student PIN</p><p className="mt-1 text-sm font-bold text-slate-900">{selected.studentPin||'-'}</p></div><div><p className="text-[11px] font-semibold uppercase text-slate-400">Standard</p><p className="mt-1 text-sm font-bold text-slate-900">{selected.standard||'-'}</p></div><div><p className="text-[11px] font-semibold uppercase text-slate-400">Tablet</p><p className="mt-1 flex items-center gap-1.5 text-sm font-bold text-slate-900"><TabletIcon className="h-4 w-4 text-blue-600"/>{selected.tabletNumber}</p></div></div>{selected.email&&<p className="mt-3 border-t border-blue-100 pt-3 text-xs text-slate-500">Email: <span className="font-semibold text-slate-700">{selected.email}</span></p>}</div>}
  <div className="grid gap-4 md:grid-cols-3"><label className="text-xs font-bold text-slate-600">Movement Type<select value={movementType} onChange={e=>setMovementType(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-blue-500">{['Vacation','Take Home','Holiday','Educational Purpose','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Start Date<input required type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-blue-500"/></label><label className="text-xs font-bold text-slate-600">Expected Return Date<input required type="date" value={returnDate} min={startDate} onChange={e=>setReturnDate(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-blue-500"/></label></div>
  <label className="block text-xs font-bold text-slate-600">Note <span className="font-normal text-slate-400">(Optional)</span><textarea value={note} onChange={e=>setNote(e.target.value)} rows={2} placeholder="Add a short note if needed..." className="mt-1.5 w-full resize-none rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-blue-500"/></label>
  {error&&<div className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</div>}
  <div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" onClick={onCancel} className="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Cancel</button><button type="submit" disabled={!selected} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50">{initial?'Update Movement':'Add Movement'}</button></div>
 </div></form>;
};