import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ClipboardList, Plus, Search, Pencil, Trash2, X, Users, ChevronRight, UserRound, Tablet as TabletIcon } from 'lucide-react';
import { Student, Tablet, TabletAssignment, UserRole, TabletMovement, TabletMovementEvent } from '../../types';
import { logAuditAction } from '../../utils/storage';
import { deleteCollectionRecord, subscribeToCollection, syncCollection } from '../../lib/db';

interface Props { movements: TabletMovement[]; students: Student[]; tablets: Tablet[]; assignments: TabletAssignment[]; activeRole: UserRole; onSave: (items: TabletMovement[]) => Promise<void> | void; }
const today=()=>new Date().toISOString().slice(0,10);
const statusOf=(m:TabletMovement):TabletMovement['status']=>m.status==='OUTSIDE'&&m.expectedReturnDate<today()?'OVERDUE':m.status;
const badge:Record<TabletMovement['status'],string>={PENDING:'bg-amber-50 text-amber-700 border-amber-200',APPROVED:'bg-blue-50 text-blue-700 border-blue-200',REJECTED:'bg-rose-50 text-rose-700 border-rose-200',OUTSIDE:'bg-violet-50 text-violet-700 border-violet-200',RETURNED:'bg-emerald-50 text-emerald-700 border-emerald-200',OVERDUE:'bg-red-50 text-red-700 border-red-200'};
const eventStatus=(e:TabletMovementEvent)=>e.endDate<today()?'Completed':e.startDate>today()?'Upcoming':'Active';
function findTablet(s:Student,tablets:Tablet[]){const id=String(s.assignedTabletId??'').trim(),number=String(s.assignedTabletNumber??'').trim().toLowerCase();return tablets.find(t=>String(t.id)===id)||tablets.find(t=>String(t.tabletNumber).trim().toLowerCase()===number)||tablets.find(t=>String(t.assignedToStudentId??'')===String(s.id));}

export const TabletMovementManagement:React.FC<Props>=({movements,students,tablets,assignments,activeRole,onSave})=>{
 const [events,setEvents]=useState<TabletMovementEvent[]>([]),[selectedEventId,setSelectedEventId]=useState(''),[eventModal,setEventModal]=useState(false),[editingEvent,setEditingEvent]=useState<TabletMovementEvent|null>(null),[studentSearch,setStudentSearch]=useState(''),[checked,setChecked]=useState<string[]>([]),[saving,setSaving]=useState(false),[deleteEvent,setDeleteEvent]=useState<TabletMovementEvent|null>(null);
 const [eventForm,setEventForm]=useState({eventName:'',startDate:today(),endDate:'',notes:''});
 useEffect(()=>subscribeToCollection<TabletMovementEvent>('movementEvents',rows=>setEvents(rows.sort((a,b)=>b.startDate.localeCompare(a.startDate)))),[]);
 const selectedEvent=events.find(e=>e.id===selectedEventId)||null;
 const selectedIds=selectedEvent?.studentIds??[];
 const eventMovements=useMemo(()=>selectedEvent?movements.filter(m=>m.eventId===selectedEvent.id):[],[movements,selectedEvent]);
 const searchResults=useMemo(()=>{const q=studentSearch.trim().toLowerCase();return students.filter(s=>{const text=`${s.studentPin??''} ${s.name??''} ${s.id??''} ${s.email??''}`.toLowerCase();return !q||text.includes(q);}).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,20);},[students,studentSearch]);
 const openCreate=()=>{setEditingEvent(null);setEventForm({eventName:'',startDate:today(),endDate:'',notes:''});setEventModal(true);};
 const openEdit=(e:TabletMovementEvent)=>{setEditingEvent(e);setEventForm({eventName:e.eventName,startDate:e.startDate,endDate:e.endDate,notes:e.notes||''});setEventModal(true);};
 const saveEvent=async(ev:React.FormEvent)=>{ev.preventDefault();if(!eventForm.eventName.trim()||!eventForm.endDate||eventForm.endDate<eventForm.startDate)return;setSaving(true);try{const now=new Date().toISOString();const next=editingEvent?events.map(e=>e.id===editingEvent.id?{...e,...eventForm,eventName:eventForm.eventName.trim(),updatedAt:now}:e):[{id:`movement-event-${Date.now()}`,eventName:eventForm.eventName.trim(),startDate:eventForm.startDate,endDate:eventForm.endDate,notes:eventForm.notes.trim(),studentIds:[],createdAt:now,updatedAt:now},...events];await syncCollection('movementEvents',events,next);setEvents(next);setEventModal(false);setSelectedEventId(editingEvent?.id||next[0].id);await logAuditAction('System User',activeRole,editingEvent?'TABLET_MOVEMENT_EVENT_UPDATED':'TABLET_MOVEMENT_EVENT_CREATED','Tablet Movement',eventForm.eventName.trim());}finally{setSaving(false);}};
 const toggleStudent=(id:string)=>setChecked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const addStudents=async()=>{if(!selectedEvent||!checked.length)return;const newIds=checked.filter(id=>!selectedIds.includes(id));if(!newIds.length){setChecked([]);return;}setSaving(true);try{const now=new Date().toISOString();const additions:TabletMovement[]=[];newIds.forEach(id=>{const s=students.find(x=>String(x.id)===id);if(!s)return;const t=findTablet(s,tablets);if(!t)return;const assignment=assignments.find(a=>String(a.studentId)===String(s.id)&&String(a.status).toLowerCase()==='active');additions.push({id:`movement-${Date.now()}-${s.id}`,assignmentId:assignment?.id||'',studentId:s.id,studentName:s.name,pinNumber:s.pinNumber,tabletId:t.id,tabletName:t.tabletName||t.tabletNumber,tabletNumber:t.tabletNumber,movementType:'Event',requestDate:today(),startDate:selectedEvent.startDate,expectedReturnDate:selectedEvent.endDate,destination:'',reason:selectedEvent.eventName,notes:selectedEvent.notes||'',status:'PENDING',createdAt:now,updatedAt:now,eventId:selectedEvent.id,eventName:selectedEvent.eventName});});if(additions.length)await onSave([...additions,...movements]);const nextEvents=events.map(e=>e.id===selectedEvent.id?{...e,studentIds:[...e.studentIds,...additions.map(x=>x.studentId)],updatedAt:now}:e);await syncCollection('movementEvents',events,nextEvents);setEvents(nextEvents);setChecked([]);await logAuditAction('System User',activeRole,'TABLET_MOVEMENT_EVENT_STUDENTS_ADDED','Tablet Movement',`${additions.length} student(s) → ${selectedEvent.eventName}`);}finally{setSaving(false);}};
 const removeStudent=async(studentId:string)=>{if(!selectedEvent)return;const now=new Date().toISOString(),nextEvents=events.map(e=>e.id===selectedEvent.id?{...e,studentIds:e.studentIds.filter(id=>id!==studentId),updatedAt:now}:e);setSaving(true);try{await syncCollection('movementEvents',events,nextEvents);setEvents(nextEvents);await logAuditAction('System User',activeRole,'TABLET_MOVEMENT_EVENT_STUDENT_REMOVED','Tablet Movement',`${studentId} ← ${selectedEvent.eventName}`);}finally{setSaving(false);}};
 const removeEvent=async()=>{if(!deleteEvent)return;setSaving(true);try{await deleteCollectionRecord('movementEvents',deleteEvent.id);const next=events.filter(e=>e.id!==deleteEvent.id);setEvents(next);if(selectedEventId===deleteEvent.id)setSelectedEventId('');setDeleteEvent(null);await logAuditAction('System User',activeRole,'TABLET_MOVEMENT_EVENT_DELETED','Tablet Movement',deleteEvent.eventName);}finally{setSaving(false);}};
 return <div className="mx-auto max-w-[1500px] space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-black text-slate-900"><ClipboardList className="h-6 w-6 text-blue-600"/>Tablet Movement</h1><p className="mt-1 text-sm text-slate-500">Create one event and add multiple students by Student PIN.</p></div><button onClick={openCreate} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-blue-700"><Plus className="h-4 w-4"/>Create Event</button></div>
  <div className="grid gap-5 lg:grid-cols-[360px_1fr]">
   <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-4"><div className="flex items-center justify-between"><h2 className="font-black text-slate-900">Movement Events</h2><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{events.length}</span></div></div><div className="max-h-[650px] overflow-y-auto">{events.length===0?<div className="p-10 text-center text-sm text-slate-500"><CalendarDays className="mx-auto mb-3 h-8 w-8 text-slate-300"/>No events created yet.</div>:events.map(e=><button key={e.id} onClick={()=>{setSelectedEventId(e.id);setStudentSearch('');setChecked([]);}} className={`w-full border-b border-slate-100 p-4 text-left transition hover:bg-slate-50 ${selectedEventId===e.id?'bg-blue-50/70':''}`}><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-100 text-blue-600"><CalendarDays className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="truncate font-bold text-slate-900">{e.eventName}</div><div className="mt-1 text-xs text-slate-500">{e.startDate} → {e.endDate}</div><div className="mt-1 text-xs font-semibold text-slate-500">{e.studentIds.length} student{e.studentIds.length===1?'':'s'} · {eventStatus(e)}</div></div><ChevronRight className="h-4 w-4 text-slate-400"/></div></button>)}</div></section>
   <section className="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{!selectedEvent?<div className="flex min-h-[500px] items-center justify-center p-8 text-center"><div><CalendarDays className="mx-auto mb-4 h-12 w-12 text-slate-300"/><h2 className="text-lg font-black text-slate-800">Select a movement event</h2><p className="mt-1 text-sm text-slate-500">Create an event or select one from the left to manage students.</p></div></div>:<>
    <div className="border-b border-slate-100 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-xl font-black text-slate-900">{selectedEvent.eventName}</h2><span className="rounded-full border border-blue-200 bg-blue-50 px-2.5 py-1 text-[11px] font-bold text-blue-700">{eventStatus(selectedEvent)}</span></div><p className="mt-1 text-sm text-slate-500">{selectedEvent.startDate} → {selectedEvent.endDate}</p>{selectedEvent.notes&&<p className="mt-2 text-sm text-slate-600">{selectedEvent.notes}</p>}</div><div className="flex gap-2"><button onClick={()=>openEdit(selectedEvent)} className="rounded-lg p-2 text-blue-600 hover:bg-blue-50" title="Edit event"><Pencil className="h-4 w-4"/></button><button onClick={()=>setDeleteEvent(selectedEvent)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50" title="Delete event"><Trash2 className="h-4 w-4"/></button></div></div></div>
    <div className="border-b border-slate-100 bg-slate-50/60 p-5"><label className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-600">Search Student</label><div className="relative max-w-2xl"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={studentSearch} onChange={e=>setStudentSearch(e.target.value)} placeholder="Search by Student PIN, name or student ID..." className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-4 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></div></div>
    <div className="border-b border-slate-100 p-5"><div className="mb-3 flex items-center justify-between"><h3 className="flex items-center gap-2 font-black text-slate-900"><Users className="h-4 w-4 text-blue-600"/>Select Students</h3><span className="text-xs font-bold text-slate-500">{checked.length} selected</span></div><div className="max-h-64 overflow-y-auto rounded-xl border border-slate-200">{searchResults.length===0?<div className="p-8 text-center text-sm text-slate-500">No students found.</div>:searchResults.map(s=>{const t=findTablet(s,tablets),already=selectedIds.includes(String(s.id)),isChecked=checked.includes(String(s.id));return <label key={s.id} className={`flex items-center gap-3 border-b border-slate-100 p-3 last:border-0 ${already?'bg-emerald-50/50 opacity-70':'cursor-pointer hover:bg-slate-50'}`}><input type="checkbox" checked={already||isChecked} disabled={already||!t} onChange={()=>toggleStudent(String(s.id))} className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"/><div className="flex min-w-0 flex-1 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-slate-100 text-slate-600"><UserRound className="h-4 w-4"/></div><div className="min-w-0"><div className="font-semibold text-slate-900">{s.name}</div><div className="text-xs text-slate-500">Student PIN: <b>{s.studentPin||'-'}</b> · {s.standard}</div></div><div className="ml-auto text-right text-xs"><div className="flex items-center justify-end gap-1 font-semibold text-slate-700"><TabletIcon className="h-3.5 w-3.5"/>{t?.tabletNumber||'No tablet assigned'}</div>{already&&<div className="mt-0.5 font-bold text-emerald-600">Already added</div>}{!already&&!t&&<div className="mt-0.5 font-bold text-rose-500">Assign tablet first</div>}</div></div></label>;})}</div><div className="mt-3 flex justify-end"><button disabled={!checked.length||saving} onClick={addStudents} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{saving?'Adding...':`Add ${checked.length||''} Selected Student${checked.length===1?'':'s'}`}</button></div></div>
    <div className="p-5"><div className="mb-3 flex items-center justify-between"><h3 className="font-black text-slate-900">Students in this Event</h3><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{selectedIds.length}</span></div><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[720px] text-left"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="p-3">Student</th><th className="p-3">Student PIN</th><th className="p-3">Tablet</th><th className="p-3">Movement</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{selectedIds.length===0?<tr><td colSpan={5} className="p-8 text-center text-sm text-slate-500">No students added to this event.</td></tr>:selectedIds.map(id=>{const s=students.find(x=>String(x.id)===String(id)),m=eventMovements.find(x=>String(x.studentId)===String(id)),t=s?findTablet(s,tablets):undefined,st=m?statusOf(m):'PENDING';return <tr key={id} className="border-t border-slate-100"><td className="p-3 font-semibold text-slate-900">{s?.name||m?.studentName||'Student'}</td><td className="p-3 text-sm font-semibold">{s?.studentPin||'-'}</td><td className="p-3 text-sm">{t?.tabletNumber||m?.tabletNumber||'-'}</td><td className="p-3"><span className={`rounded-full border px-2.5 py-1 text-[11px] font-bold ${badge[st]}`}>{st}</span></td><td className="p-3 text-right"><button onClick={()=>removeStudent(String(id))} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50" title="Remove student"><X className="h-4 w-4"/></button></td></tr>;})}</tbody></table></div></div>
   </>}</section>
  </div>
  {eventModal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={saveEvent} className="w-full max-w-lg overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-lg font-black text-slate-900">{editingEvent?'Edit Event':'Create Movement Event'}</h2><p className="mt-0.5 text-xs text-slate-500">Set one date range and add students later.</p></div><button type="button" onClick={()=>setEventModal(false)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X className="h-4 w-4"/></button></div><div className="space-y-4 p-5"><div><label className="mb-1.5 block text-sm font-bold text-slate-700">Event Name</label><input autoFocus required value={eventForm.eventName} onChange={e=>setEventForm(v=>({...v,eventName:e.target.value}))} placeholder="e.g. Summer Vacation" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-blue-500"/></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-sm font-bold text-slate-700">From Date</label><input required type="date" value={eventForm.startDate} onChange={e=>setEventForm(v=>({...v,startDate:e.target.value}))} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-blue-500"/></div><div><label className="mb-1.5 block text-sm font-bold text-slate-700">To Date</label><input required type="date" min={eventForm.startDate} value={eventForm.endDate} onChange={e=>setEventForm(v=>({...v,endDate:e.target.value}))} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-blue-500"/></div></div><div><label className="mb-1.5 block text-sm font-bold text-slate-700">Note <span className="font-normal text-slate-400">(Optional)</span></label><textarea rows={3} value={eventForm.notes} onChange={e=>setEventForm(v=>({...v,notes:e.target.value}))} placeholder="Optional event note..." className="w-full resize-none rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-blue-500"/></div><div className="flex justify-end gap-3 border-t border-slate-100 pt-4"><button type="button" onClick={()=>setEventModal(false)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?'Saving...':editingEvent?'Save Changes':'Create Event'}</button></div></div></form></div>}
  {deleteEvent&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h3 className="text-lg font-black text-slate-900">Delete Movement Event?</h3><p className="mt-2 text-sm leading-6 text-slate-600">Delete <b>{deleteEvent.eventName}</b>? The event will be removed, while existing movement history remains.</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setDeleteEvent(null)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold">Cancel</button><button disabled={saving} onClick={removeEvent} className="rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-bold text-white">{saving?'Deleting...':'Yes, Delete'}</button></div></div></div>}
 </div>;
};
