import { useEffect, useState } from 'react';
interface StudentProfile { name: string; standard: string; coachingType: string; roomNumber: string; wingNumber: string; tabletId?: string; }
interface ActiveSession { sessionToken: string; studentId: string; studentName: string; tabletId: string; startedAt: string; student?: StudentProfile; }
interface CheckoutRequest { id: string; status: 'pending' | 'approved' | 'rejected'; requestedAt: string; }
const SESSION_KEY = 'teb_student_session_token'; const REGISTERED_KEY = 'teb_student_registered_id';
function normalizePin(value: string) { return value.trim().replace(/^PIN-/i, '').replace(/\D/g, '').slice(0, 4); }
function generatePin() { return String(Math.floor(Math.random() * 10000)).padStart(4, '0'); }
function formatElapsed(startedAt: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(startedAt).getTime()) / 1000)); const h = String(Math.floor(seconds / 3600)).padStart(2, '0'); const m = String(Math.floor((seconds % 3600) / 60)).padStart(2, '0'); const s = String(seconds % 60).padStart(2, '0'); return `${h}:${m}:${s}`; }

export function StudentTabletApp() {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [name, setName] = useState(''); const [pin, setPin] = useState(''); const [standard, setStandard] = useState('Std 8'); const [coachingType, setCoachingType] = useState('Coaching'); const [roomNumber, setRoomNumber] = useState(''); const [wingNumber, setWingNumber] = useState(''); const [generatedPin, setGeneratedPin] = useState(''); const [session, setSession] = useState<ActiveSession | null>(null); const [checkoutRequest, setCheckoutRequest] = useState<CheckoutRequest | null>(null); const [elapsed, setElapsed] = useState('00:00:00'); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const student = session?.student;
  const alreadyRegistered = Boolean(localStorage.getItem(REGISTERED_KEY));

  useEffect(() => { let cancelled = false; async function restore() { const token = localStorage.getItem(SESSION_KEY); if (!token) { if (!cancelled) setLoading(false); return; } try { const response = await fetch('/api/student/session', { headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' } }); const result = await response.json().catch(() => ({})); if (!response.ok || !result?.session) throw new Error(result?.error || 'Session expired. Please login again.'); if (!cancelled) { setSession(result.session); setMessage('Active session restored.'); } } catch (e) { localStorage.removeItem(SESSION_KEY); if (!cancelled) setError(e instanceof Error ? e.message : 'Session could not be restored.'); } finally { if (!cancelled) setLoading(false); } } restore(); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (!session) return; setElapsed(formatElapsed(session.startedAt)); const timer = window.setInterval(() => setElapsed(formatElapsed(session.startedAt)), 1000); return () => window.clearInterval(timer); }, [session]);
  async function login() { setError(''); setMessage(''); const cleanName = name.trim(); const cleanPin = normalizePin(pin); if (!cleanName) { setError('Please enter Student Name.'); return; } if (!/^\d{4}$/.test(cleanPin)) { setError('Student PIN must be exactly 4 digits.'); return; } setLoading(true); try { const response = await fetch('/api/student/activate', { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ name: cleanName, pin: cleanPin }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result?.error || `Login failed (${response.status}).`); localStorage.setItem(SESSION_KEY, result.session.sessionToken); setSession(result.session); setName(''); setPin(''); setMessage('Student signed in successfully. Attendance is now IN.'); } catch (e) { setError(e instanceof Error ? e.message : 'Login failed.'); } finally { setLoading(false); } }
  async function registerStudent() { setError(''); setMessage(''); setGeneratedPin(''); if (alreadyRegistered) { setError('This device has already completed student registration.'); return; } const cleanName = name.trim(); const cleanRoom = roomNumber.trim(); const cleanWing = wingNumber.trim(); if (!cleanName || !cleanRoom || !cleanWing) { setError('Student Name, Room Number and Wing Number are required.'); return; } setLoading(true); try { let response: Response | null = null; let result: any = {}; let appPin = ''; for (let attempt = 0; attempt < 5; attempt++) { appPin = generatePin(); response = await fetch('/api/student/register', { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ name: cleanName, pin: appPin, standard, coachingType, roomNumber: cleanRoom, wingNumber: cleanWing }) }); result = await response.json().catch(() => ({})); if (response.ok) break; if (response.status !== 409) throw new Error(result?.error || `Registration failed (${response.status}).`); } if (!response?.ok) throw new Error(result?.error || 'Registration failed.'); localStorage.setItem(REGISTERED_KEY, String(result.student?.id || 'registered')); setGeneratedPin(appPin); setMessage('Registration successful. Save the App PIN. Your registration is now locked and awaits Admin approval.'); setName(''); setPin(''); setRoomNumber(''); setWingNumber(''); setMode('login'); } catch (e) { setError(e instanceof Error ? e.message : 'Registration failed.'); } finally { setLoading(false); } }
  async function requestCheckout() { if (!session) return; setError(''); setMessage(''); setLoading(true); try { const response = await fetch('/api/student/checkout-request', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.sessionToken}` }, body: '{}' }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result?.error || 'Could not submit checkout request.'); setCheckoutRequest(result.request); setMessage('Checkout request sent. Please wait for Admin approval.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not submit checkout request.'); } finally { setLoading(false); } }
  if (loading && !session && !error) return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-5 text-slate-900"><section className="w-full max-w-md rounded-3xl bg-white shadow-xl border border-slate-200 p-7 text-center"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-600 text-2xl font-bold text-white">TEB</div><p className="font-semibold">Checking student session...</p></section></main>;
  return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-5 text-slate-900"><section className="w-full max-w-md rounded-3xl bg-white shadow-xl border border-slate-200 p-7"><div className="text-center mb-7"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-600 text-2xl font-bold text-white">TEB</div><h1 className="text-2xl font-bold">Student App</h1><p className="mt-1 text-sm text-slate-500">Secure student login and attendance</p></div>
    {!session ? <>{!alreadyRegistered && <div className="flex mb-6 rounded-xl bg-slate-100 p-1"><button type="button" onClick={() => { setMode('login'); setError(''); setMessage(''); }} className={`flex-1 rounded-lg px-3 py-3 text-sm font-semibold ${mode === 'login' ? 'bg-white shadow text-slate-900' : 'text-slate-500'}`}>Existing Student</button><button type="button" onClick={() => { setMode('register'); setError(''); setMessage(''); }} className={`flex-1 rounded-lg px-3 py-3 text-sm font-semibold ${mode === 'register' ? 'bg-white shadow text-slate-900' : 'text-slate-500'}`}>First Time</button></div>}
      {mode === 'login' || alreadyRegistered ? <div className="space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium">Student Name</span><input value={name} onChange={e => setName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') login(); }} placeholder="Enter student name" className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-indigo-500" autoFocus /></label><label className="block"><span className="mb-1.5 block text-sm font-medium">Student PIN</span><input value={pin} maxLength={4} onChange={e => setPin(normalizePin(e.target.value))} onKeyDown={e => { if (e.key === 'Enter') login(); }} inputMode="numeric" pattern="[0-9]*" type="password" placeholder="Enter 4-digit PIN" className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-indigo-500" /></label><button type="button" disabled={loading || !name.trim() || !pin.trim()} onClick={login} className="w-full rounded-xl bg-indigo-600 px-4 py-3.5 font-semibold text-white disabled:opacity-60">{loading ? 'Signing in...' : 'Login & Start'}</button><p className="text-center text-xs text-slate-500">{alreadyRegistered ? 'Registration is already completed on this device. Admin approval is required before first login.' : 'Enter Student Name and 4-digit App PIN. Tablet is assigned by Admin.'}</p></div> : <div className="space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium">Student Name</span><input value={name} onChange={e => setName(e.target.value)} placeholder="Enter student name" className="w-full rounded-xl border border-slate-300 px-4 py-3" autoFocus /></label><div className="grid grid-cols-2 gap-3"><select value={standard} onChange={e => setStandard(e.target.value)} className="w-full rounded-xl border border-slate-300 px-4 py-3"><option>Std 8</option><option>Std 9</option><option>Std 10</option><option>Std 11</option><option>Std 12</option></select><select value={coachingType} onChange={e => setCoachingType(e.target.value)} className="w-full rounded-xl border border-slate-300 px-4 py-3"><option>Coaching</option><option>Non-Coaching</option></select></div><div className="grid grid-cols-2 gap-3"><input value={roomNumber} onChange={e => setRoomNumber(e.target.value)} placeholder="Room Number" className="w-full rounded-xl border border-slate-300 px-4 py-3" /><input value={wingNumber} onChange={e => setWingNumber(e.target.value)} placeholder="Wing Number" className="w-full rounded-xl border border-slate-300 px-4 py-3" /></div><button type="button" disabled={loading || !name.trim() || !roomNumber.trim() || !wingNumber.trim()} onClick={registerStudent} className="w-full rounded-xl bg-indigo-600 px-4 py-3.5 font-semibold text-white disabled:opacity-60">{loading ? 'Registering...' : 'Register Student'}</button><p className="text-center text-xs text-slate-500">After successful registration, this form is permanently hidden on this device.</p></div>}
    </> : <div className="space-y-5"><div className="rounded-2xl bg-emerald-50 p-5 text-center"><p className="text-sm font-medium text-emerald-700">Session Active • IN</p><p className="mt-1 text-xl font-bold">{session.studentName}</p><p className="mt-1 text-sm text-emerald-700">Assigned Tablet: {session.tabletId}</p><p className="mt-4 text-3xl font-mono font-bold text-emerald-900">{elapsed}</p></div>{student && <div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-500">Standard</span><p className="font-semibold">{student.standard}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-500">Type</span><p className="font-semibold">{student.coachingType}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-500">Room</span><p className="font-semibold">{student.roomNumber}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-500">Wing</span><p className="font-semibold">{student.wingNumber}</p></div></div>}{checkoutRequest?.status === 'pending' ? <div className="rounded-2xl bg-amber-50 border border-amber-200 p-4 text-center text-sm font-semibold text-amber-800">Checkout request pending. Admin approval is required.</div> : <button type="button" disabled={loading} onClick={requestCheckout} className="w-full rounded-xl bg-slate-900 px-4 py-3.5 font-semibold text-white disabled:opacity-60">{loading ? 'Requesting...' : 'REQUEST CHECKOUT'}</button>}</div>}
    {message && <p className="mt-5 rounded-xl bg-blue-50 px-4 py-3 text-sm text-blue-700">{message}</p>}{error && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<p className="mt-6 text-center text-xs text-slate-400">TEB Management • Student access only</p></section></main>;
}
