import { useEffect, useState } from 'react';

interface StudentProfile { name: string; standard: string; coachingType: string; roomNumber: string; wingNumber: string; tabletId?: string; }
interface ActiveSession { sessionToken: string; studentId: string; studentName: string; tabletId: string; startedAt: string; student?: StudentProfile; }
const SESSION_KEY = 'teb_student_session_token';
function normalizePin(value: string) { return value.trim().replace(/^PIN-/i, '').replace(/\D/g, '').slice(0, 4); }
function formatElapsed(startedAt: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(startedAt).getTime()) / 1000)); const h = String(Math.floor(seconds / 3600)).padStart(2, '0'); const m = String(Math.floor((seconds % 3600) / 60)).padStart(2, '0'); const s = String(seconds % 60).padStart(2, '0'); return `${h}:${m}:${s}`; }

export function StudentTabletApp() {
  const [pin, setPin] = useState(''); const [session, setSession] = useState<ActiveSession | null>(null); const [elapsed, setElapsed] = useState('00:00:00'); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const student = session?.student;

  useEffect(() => { let cancelled = false; async function restore() { const token = localStorage.getItem(SESSION_KEY); if (!token) { if (!cancelled) setLoading(false); return; } try { const response = await fetch('/api/student/session', { headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' } }); const result = await response.json().catch(() => ({})); if (!response.ok || !result?.session) throw new Error(result?.error || 'Session expired. Please login again.'); if (!cancelled) { setSession(result.session); setMessage('Active session restored.'); } } catch (e) { localStorage.removeItem(SESSION_KEY); if (!cancelled) setError(e instanceof Error ? e.message : 'Session could not be restored.'); } finally { if (!cancelled) setLoading(false); } } restore(); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (!session) return; setElapsed(formatElapsed(session.startedAt)); const timer = window.setInterval(() => setElapsed(formatElapsed(session.startedAt)), 1000); return () => window.clearInterval(timer); }, [session]);

  async function login() { setError(''); setMessage(''); const cleanPin = normalizePin(pin); if (cleanPin.length !== 4) { setError('App PIN must be exactly 4 digits.'); return; } setLoading(true); try { const response = await fetch('/api/student/activate', { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ pin: cleanPin }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result?.error || `Login failed (${response.status}).`); if (!result?.session) throw new Error('Login response is invalid.'); localStorage.setItem(SESSION_KEY, result.session.sessionToken); setSession(result.session); setPin(''); setMessage('Student signed in successfully.'); } catch (e) { setError(e instanceof Error ? e.message : 'Login failed.'); } finally { setLoading(false); } }
  async function returnTablet() { if (!session) return; setError(''); setMessage(''); setLoading(true); try { const response = await fetch('/api/student/return', { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ sessionToken: session.sessionToken }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result?.error || 'Could not return the tablet.'); localStorage.removeItem(SESSION_KEY); setSession(null); setElapsed('00:00:00'); setPin(''); setMessage(`Tablet checked out. Session duration: ${result.durationMinutes} minute(s).`); } catch (e) { setError(e instanceof Error ? e.message : 'Could not return the tablet.'); } finally { setLoading(false); } }

  if (loading && !session && !error) return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-5 text-slate-900"><section className="w-full max-w-md rounded-3xl bg-white shadow-xl border border-slate-200 p-7 text-center"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-600 text-2xl font-bold text-white">TEB</div><p className="font-semibold">Checking student session...</p></section></main>;
  return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-5 text-slate-900"><section className="w-full max-w-md rounded-3xl bg-white shadow-xl border border-slate-200 p-7"><div className="text-center mb-7"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-600 text-2xl font-bold text-white">TEB</div><h1 className="text-2xl font-bold">Student App</h1><p className="mt-1 text-sm text-slate-500">Login with the App PIN provided by Admin</p></div>
    {!session ? <div className="space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium">4-Digit App PIN</span><input value={pin} maxLength={4} onChange={e => setPin(normalizePin(e.target.value))} inputMode="numeric" pattern="[0-9]{4}" type="password" placeholder="Enter 4 digit App PIN" className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-indigo-500" /></label><button type="button" disabled={loading || normalizePin(pin).length !== 4} onClick={login} className="w-full rounded-xl bg-indigo-600 px-4 py-3.5 font-semibold text-white disabled:opacity-60">{loading ? 'Signing in...' : 'Login & Start'}</button><p className="text-center text-xs text-slate-500">Students cannot register or create a PIN from this app. Admin creates the student and provides the App PIN.</p></div> : <div className="space-y-5"><div className="rounded-2xl bg-emerald-50 p-5 text-center"><p className="text-sm font-medium text-emerald-700">Session Active • IN</p><p className="mt-1 text-xl font-bold">{session.studentName}</p><p className="mt-1 text-sm text-emerald-700">Assigned Tablet: {session.tabletId}</p><p className="mt-4 text-3xl font-mono font-bold text-emerald-900">{elapsed}</p></div>{student && <div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-500">Standard</span><p className="font-semibold">{student.standard}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-500">Type</span><p className="font-semibold">{student.coachingType}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-500">Room</span><p className="font-semibold">{student.roomNumber}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-500">Wing</span><p className="font-semibold">{student.wingNumber}</p></div></div>}<button type="button" disabled={loading} onClick={returnTablet} className="w-full rounded-xl bg-slate-900 px-4 py-3.5 font-semibold text-white disabled:opacity-60">{loading ? 'Checking out...' : 'CHECKOUT / RETURN TABLET'}</button></div>}
    {message && <p className="mt-5 rounded-xl bg-blue-50 px-4 py-3 text-sm text-blue-700">{message}</p>}{error && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<p className="mt-6 text-center text-xs text-slate-400">TEB Management • Student access only</p></section></main>;
}
