import React, { useState } from 'react';
import { Download, ExternalLink, Copy, Check, Smartphone, ShieldCheck } from 'lucide-react';

const APK_URL = 'https://github.com/meet7573/teb-mengment-/releases/download/student-apk-latest/teb-student.apk';
const STUDENT_APP_URL = 'https://teb-mengment.onrender.com/student';

export const StudentDownload: React.FC = () => {
  const [copied, setCopied] = useState(false);

  const copyLink = async () => {
    try {
      await navigator.clipboard.writeText(APK_URL);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 p-5 text-slate-900 sm:p-8">
      <div className="mx-auto max-w-2xl">
        <div className="mb-6 flex items-center justify-between">
          <div>
            <p className="text-xs font-black uppercase tracking-widest text-indigo-600">TEB Management</p>
            <h1 className="mt-1 text-2xl font-black">Student App</h1>
          </div>
          <Smartphone className="h-8 w-8 text-indigo-600" />
        </div>

        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
          <div className="rounded-2xl bg-indigo-50 p-5">
            <div className="flex items-start gap-3">
              <ShieldCheck className="mt-0.5 h-6 w-6 shrink-0 text-indigo-600" />
              <div>
                <h2 className="font-bold">Student-only tablet application</h2>
                <p className="mt-1 text-sm leading-6 text-slate-600">
                  Students use the app with the Tablet ID and their PIN. The admin dashboard and Supabase credentials are not included in the APK.
                </p>
              </div>
            </div>
          </div>

          <div className="mt-6 space-y-3">
            <a href={APK_URL} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-5 py-4 font-bold text-white shadow-sm transition hover:bg-indigo-700">
              <Download className="h-5 w-5" />
              Download Student APK
            </a>
            <a href={STUDENT_APP_URL} target="_blank" rel="noreferrer" className="flex w-full items-center justify-center gap-2 rounded-2xl border border-slate-300 bg-white px-5 py-4 font-bold text-slate-800 transition hover:bg-slate-50">
              <ExternalLink className="h-5 w-5" />
              Open Student Web App
            </a>
            <button type="button" onClick={copyLink} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-slate-50 px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-100">
              {copied ? <Check className="h-4 w-4 text-emerald-600" /> : <Copy className="h-4 w-4" />}
              {copied ? 'Download link copied' : 'Copy APK download link'}
            </button>
          </div>

          <div className="mt-7 border-t border-slate-100 pt-5">
            <h3 className="text-sm font-bold">How students use it</h3>
            <ol className="mt-3 space-y-2 text-sm text-slate-600">
              <li>1. Install the APK on the tablet.</li>
              <li>2. Open Student Tablet.</li>
              <li>3. Enter the Tablet ID generated by the admin and the student PIN.</li>
              <li>4. Tap Activate Tablet.</li>
              <li>5. When finished, tap Return Tablet.</li>
            </ol>
          </div>
        </section>
      </div>
    </div>
  );
};
