import { Router } from 'express';
import { randomUUID } from 'node:crypto';
const MAX_FILE_BYTES = 5 * 1024 * 1024; const ALLOWED_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp']); const BUCKETS = { student: 'student-photos', tablet: 'tablet-photos' } as const; type PhotoKind = keyof typeof BUCKETS; type PhotoConfig = { supabaseUrl?: string; supabaseKey?: string };
const isAdminRole = (role: string | undefined) => role === 'Admin' || role === 'Super Admin'; const getBucket = (kind: unknown): PhotoKind | null => kind === 'student' || kind === 'tablet' ? kind : null;
function extension(type: string) { return type === 'image/jpeg' ? 'jpg' : type === 'image/png' ? 'png' : 'webp'; }
function decode(dataUrl: string) { const match = /^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(dataUrl); if (!match) throw new Error('Invalid image data.'); const buffer = Buffer.from(match[2], 'base64'); if (!buffer.length || buffer.length > MAX_FILE_BYTES) throw new Error('Image must be 5 MB or less.'); return { type: match[1], buffer }; }
async function storage(url: string, key: string, pathname: string, options: RequestInit = {}) { return fetch(`${url}/storage/v1/${pathname}`, { ...options, headers: { Authorization: `Bearer ${key}`, apikey: key, ...(options.headers || {}) } }); }
export function createPhotoRouter(config: PhotoConfig) {
  const router = Router(); const url = config.supabaseUrl?.replace(/\/$/, ''); const key = config.supabaseKey; const ready = () => Boolean(url && key);
  router.post('/upload', async (req, res) => { if (!isAdminRole(String(req.headers['x-admin-role'] || ''))) return res.status(403).json({ error: 'Admin access required.' }); if (!ready()) return res.status(503).json({ error: 'Photo storage is not configured.' }); try { const kind = getBucket(req.body?.kind); const itemId = String(req.body?.itemId || '').trim(); const contentType = String(req.body?.contentType || ''); if (!kind || !itemId || !ALLOWED_TYPES.has(contentType)) return res.status(400).json({ error: 'Valid photo type and item are required.' }); const decoded = decode(String(req.body?.dataUrl || '')); const path = `${itemId}/${randomUUID()}.${extension(decoded.type)}`; const uploaded = await storage(url!, key!, `object/${BUCKETS[kind]}/${path}`, { method: 'POST', headers: { 'Content-Type': decoded.type, 'x-upsert': 'false' }, body: decoded.buffer }); if (!uploaded.ok) return res.status(502).json({ error: 'Photo storage upload failed.' }); const signed = await storage(url!, key!, `object/sign/${BUCKETS[kind]}/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ expiresIn: 3600 }) }); if (!signed.ok) return res.status(502).json({ error: 'Photo uploaded but preview URL failed.' }); const data = await signed.json(); return res.json({ path, url: data.signedURL || data.signedUrl }); } catch (error) { console.error('Photo upload failed:', error); return res.status(400).json({ error: error instanceof Error ? error.message : 'Photo upload failed.' }); } });
  router.get('/signed-url', async (req, res) => { if (!isAdminRole(String(req.headers['x-admin-role'] || ''))) return res.status(403).json({ error: 'Admin access required.' }); if (!ready()) return res.status(503).json({ error: 'Photo storage is not configured.' }); try { const kind = getBucket(req.query.kind); const path = String(req.query.path || '').trim(); if (!kind || !path || path.includes('..') || path.startsWith('/')) return res.status(400).json({ error: 'Invalid photo path.' }); const response = await storage(url!, key!, `object/sign/${BUCKETS[kind]}/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ expiresIn: 3600 }) }); if (!response.ok) return res.status(404).json({ error: 'Photo not found.' }); const data = await response.json(); return res.json({ url: data.signedURL || data.signedUrl }); } catch { return res.status(500).json({ error: 'Could not create photo URL.' }); } });
  router.post('/delete', async (req, res) => { if (!isAdminRole(String(req.headers['x-admin-role'] || ''))) return res.status(403).json({ error: 'Admin access required.' }); if (!ready()) return res.status(503).json({ error: 'Photo storage is not configured.' }); try { const kind = getBucket(req.body?.kind); const path = String(req.body?.path || '').trim(); if (!kind || !path || path.includes('..') || path.startsWith('/')) return res.status(400).json({ error: 'Invalid photo path.' }); const response = await storage(url!, key!, `object/${BUCKETS[kind]}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prefixes: [path] }) }); if (!response.ok) return res.status(502).json({ error: 'Photo deletion failed.' }); return res.json({ ok: true }); } catch { return res.status(500).json({ error: 'Photo deletion failed.' }); } });
  return router;
}
