import React, { useEffect, useState } from 'react';
import { CheckCircle2, Clock3, XCircle } from 'lucide-react';

interface CheckoutRequest { id: string; studentName: string; studentId: string; tabletId: string; requestedAt: string; status: string; }
export const CheckoutRequestsPanel: React.FC = () => {
  const [requests, setRequests] = useState<CheckoutRequest[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async () => { const token = localStorage.getItem('stm_admin_session_token') || ''; if (!token) return; try { const r = await fetch('/api/admin/checkout-requests', { headers: { Authorization: `Bearer ${token}` } }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d?.error || 'Could not load checkout requests.'); setRequests(Array.isArray(d.requests) ? d.requests : []); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load checkout requests.'); } };
  useEffect(() => { load(); const timer = window.setInterval(load, 10000); return () => window.clearInterval(timer); }, []);
  const decide = async (id: string, decision: 'approved' | 'rejected') => { setLoading(true); setError(''); try { const token = localStorage.getItem('stm_admin_session_token') || ''; const r = await fetch(`/api/admin/checkout-requests/${encodeURIComponent(id)}/decision`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ decision }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d?.error || 'Could not update request.'); setRequests(items => items.filter(item => item.id !== id)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update request.'); } finally { setLoading(false); } };
  return <section className="mt-6 bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden"><div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between"><div><h3 className="font-bold text-slate-900 flex items-center gap-2"><Clock3 className="w-5 h-5 text-amber-600" />Pending Checkout Requests</h3><p className="text-xs text-slate-500 mt-1">Students can request checkout, but only Admin can approve OUT.</p></div><span className="rounded-full bg-amber-50 text-amber-700 px-3 py-1 text-xs font-bold">{requests.length} Pending</span></div>{error && <div className="m-4 rounded-xl bg-red-50 text-red-700 px-4 py-3 text-sm">{error}</div>}{requests.length === 0 ? <div className="p-8 text-center text-sm text-slate-500">No pending checkout requests.</div> : <div className="divide-y divide-slate-100">{requests.map(request => <div key={request.id} className="px-6 py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><p className="font-bold text-slate-900">{request.studentName}</p><p className="text-xs text-slate-500 mt-1">Tablet: {request.tabletId} • Requested: {new Date(request.requestedAt).toLocaleString()}</p></div><div className="flex gap-2"><button disabled={loading} onClick={() => decide(request.id, 'rejected')} className="inline-flex items-center gap-1 px-3 py-2 rounded-xl bg-red-50 text-red-700 font-semibold disabled:opacity-50"><XCircle className="w-4 h-4" />Reject</button><button disabled={loading} onClick={() => decide(request.id, 'approved')} className="inline-flex items-center gap-1 px-3 py-2 rounded-xl bg-emerald-50 text-emerald-700 font-semibold disabled:opacity-50"><CheckCircle2 className="w-4 h-4" />Approve OUT</button></div></div>)}</div>}</section>;
};
